### ISSUE TITLE
Kitap dökümanı şu anda mevcut değil

### ISSUE THREAD

**Issue by phoique** [mstrYoda/kubernetes-kitap#1]
Merhabalar, 

Kitap dökümanı github.io üzerinde yüklü değil sadece konu başlıkları mevcut. Ne zaman yükleyeceksiniz acaba.

Teşekkür ederim.

**Comment by mstrYoda** [comment]
@phoique selamlar, ilk etapta kabataslak müfredat oluşturmaya çalıştım, fırsat buldukça içeriği güncelleyeceğim. Aslında burada ilk hedeflediğim şey bir kısmını paylaştıktan sonra belirli konularda uzmanlaşmış kişileri içeriği doldurmaya teşvik etmek.

**Comment by phoique** [comment]
@mstrYoda Selamlar, readme file da hazırladık sunduk yazınca bende doküman hazır yüklenmeyi bekliyor sandım. Teşekkür ederim bilgilendirdiğiniz için.
