### ISSUE TITLE
K3d Nedir Basit Olarak kullanımı ve Kurulumu

### ISSUE THREAD

**Issue by MuratSs** [mstrYoda/kubernetes-kitap#18]
K3d kısmına eklenmesi gerekenler:
- Cluster kurulumu
- K3D Load Balancer Ayarları
- Servis kullanımı
- Demo nginx server kurulumu
- 2.2 - K3D NodePort Ayarları
- .... ve dahası

**Comment by mstrYoda** [comment]
Eklendi, teşekkürler
