### ISSUE TITLE
Dokumanlara erisilememe sorunu

### ISSUE THREAD

**Issue by melihayyildiz** [mstrYoda/kubernetes-kitap#21]
Merhaba,

Kubernetes Cluster Mimarisi basligindan sonraki tum dokumanlarda 404 hatasi alinmakta

**Comment by MuratSs** [comment]
kitabın o bölümlerinin hala yazılmamış olduğundan bu sorun.

**Comment by melihayyildiz** [comment]
> kitabın o bölümlerinin hala yazılmamış olduğundan bu sorun.

Basliklar link olunca erisilebilir izlenimi yaratti. Tesekkurler. Simdiden elinize saglik.
