### ISSUE TITLE
Kubernetes Kitap Organizasyon

### ISSUE THREAD

**Issue by kemalmeler** [mstrYoda/kubernetes-kitap#50]
Selam,

Kubernetes Kitap projesi için, ayrı bir organization açılması konusu gündemde mi? 

Çünkü bu iş büyük bir iş ve daha da büyüyecek gibi görünüyor.

**Comment by mstrYoda** [comment]
Selamlar, şu an için böyle bir ihtiyaç ve gereklilik olduğunu düşünmüyorum. Teşekkürler.
