### ISSUE TITLE
Worker Node Elemanları çalışmıyor

### ISSUE THREAD

**Issue by MuratTopcu** [mstrYoda/kubernetes-kitap#60]
Linke tıkladığımda 404 veriyor https://mstryoda.github.io/kubernetes-kitap/#/data-plane

**Comment by mstrYoda** [comment]
İlginiz için teşekkürler, bazı başlıklar henüz doldurulmadığı için 404 veriyor. En kısa zamanda tamamlamaya çalışacağım.
